name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Packaging
        uses: actions/checkout@v2
        
      - uses: papeloto/action-zip@v1
        with:
          files: base.toc base.lua
          dest: OAH.zip
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: OAH.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

